build:
  version: "3.0"

user:
  message: "Welcome to MagicBox ProductCatalog related local APIs"
  contactDetails:
    name: "Sagar Mitkari - Developer"
    email: "sagar.m@magicbox.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1323
